- name: Installing Wordpress using wget
  command: wget https://wordpress.org/latest.tar.gz
  command: mv latest.tar.gz /tmp/wordpress.tar.gz

- name: Extract WordPress
  unarchive:
    src: /tmp/wordpress.tar.gz
    dest: /var/www/html/
    remote_src: yes
    creates: /var/www/html/wordpress

- name: Copy wp-config file
  template:
    src: wp-config.php.j2
    dest: /var/www/html/wordpress/wp-config.php

- name: Set permissions
  file:
    path: /var/www/html/wordpress
    state: directory
    recurse: yes
    owner: www-data
    group: www-data

- name: Restart Apache
  service:
    name: apache2
    state: restarted
